export enum TASK_TYPE {
  HELP = 'HELP',
  SKILL = 'SKILL',
  COMMUNITY = 'COMMUNITY',
}

export enum REWARD_TYPE {
  FREE = 'FREE',
  PAID = 'PAID',
}

export enum TASK_STATUS {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ORDER_STATUS {
  ACCEPTED = 'ACCEPTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum USER_ROLE {
  USER = 'USER',
  ADMIN = 'ADMIN',
}
